SELECT LOCAL_NET_ADDRESS AS IP_NAME
FROM SYS.DM_EXEC_CONNECTIONS AS T1.
WHERE T1.SESSION_ID = @@SPID;

SELECT TOP (1) AS IP_NAME
FROM SYS.DM_EXEC_CONNECTIONS AS T1
WHERE T1.LOCAL_NET_ADDRESS IS NOT NULL;


SELECT CONNECTIONPROPERTY('192.168.0.29') as IP 


SELECT @@IDENTITY

SELECT * FROM HRTEST.dbo.SUGGESTION

INSERT INTO SUGGESTION (NAMESURNAME,SUGGESTIONTEXT,DATE_) VALUES ('Mehmet','Test',GETDATE());--SELECT @@IDENTITY;