
--EXEC XP_READERRORLOG

CREATE TABLE #LOG (
LOGDATE DATETIME, PROCESSINFO VARCHAR(100), TEXT VARCHAR(MAX)) --SANAL TEMP TABLO OLUÞTURUYORUZ. TEMP TABLO # iþareti ile oluþturulur.

SELECT * FROM #LOG

INSERT INTO #LOG EXEC XP_READERRORLOG


SELECT * FROM #LOG WHERE TEXT LIKE 'login failed%' AND LOGDATE>= DATEADD(MINUTE,-3,GETDATE())


SELECT GETDATE(),DATEADD(MINUTE,-3,GETDATE()) -- 3 DAKÝKA EKSÝK DÖNDÜRÜR.



--Örnek Declare DEÐÝÞKEN OLUÞTURDUK.
DECLARE @IP AS VARCHAR(100)
DECLARE @COUNT AS INT
DECLARE @BEGDATE AS DATETIME 
DECLARE @ENDDATE AS DATETIME 
DECLARE @TEXT AS VARCHAR(max) = ''
DECLARE @MSG AS VARCHAR(2000) = ''


SET @MSG = ' Your system is under attack! A machine with ip'
SET @MSG = @MSG + @IP
SET @MSG = @MSG + ' has tried' + CONVERT(VARCHAR,@COUNT) + ' wrong password between'
SET @MSG = @MSG + CONVERT(VARCHAR,@BEGDATE,108)+ ' AND ' + CONVERT(VARCHAR,@ENDDATE,108)

SELECT @MSG

SELECT @COUNT = COUNT(*),@BEGDATE=MIN(LOGDATE),@ENDDATE = MAX(LOGDATE),@TEXT = TEXT
FROM #LOG WHERE TEXT LIKE 'Login failed%' AND LOGDATE >= DATEADD(MINUTE,-3,GETDATE())
GROUP BY TEXT
HAVING COUNT (LOGDATE)>100

SELECT @COUNT,@BEGDATE,@ENDDATE,@TEXT


DECLARE @SEQ AS INT
DECLARE @IP AS VARCHAR(20)






SELECT * FROM master.DBO.splitWithSeq(@TEXT,' ')
where items = '[CLIENT:'

SELECT @IP = items FROM master.DBO.splitWithSeq(@TEXT,' ')
where SEQ = @SEQ +1
SET @IP = REPLACE(@IP,']','')
SELECT @IP


 --'Your system is under attack! A machine with ip 192.168.84.128 has tried 551 wrong password between 14:25 ile 14:38'
