ALTER PROCEDURE BRUTE_FORCE_DETECTION
AS 

--EXEC XP_READERRORLOG --Log Kayýtlarýný listeler.
--TEMP Tablo Diez iþaretiyle oluþturulur.


INSERT INTO #LOG EXEC XP_READERRORLOG
--CREATE TABLE #LOG (LOGDATE DATETIME,PROCESSINFO VARCHAR(100),TEXT VARCHAR(MAX)) --TEMP TABLO OLUÞTURMA.


--SELECT * FROM #LOG WHERE TEXT LIKE 'login failed%' and LOGDATE >=DATEADD(MINUTE,-3,GETDATE()) 

--TRUNCATE TABLE #LOG




DECLARE @IP AS VARCHAR(100) = '192.168.84.128'
DECLARE @COUNT AS INT 
DECLARE @BEGDATE AS DATETIME 
DECLARE @ENDDATE AS DATETIME 
DECLARE @TEXT AS VARCHAR(1000) = '';
DECLARE @MSH AS VARCHAR(1000) = '';

SELECT @COUNT = COUNT(*),@BEGDATE = MIN(LOGDATE), @ENDDATE = MAX(LOGDATE),@TEXT = TEXT
FROM #LOG WHERE TEXT LIKE 'Loging failed%' AND LOGDATE >=DATEADD(MINUTE,-3,GETDATE())
GROUP BY TEXT
HAVING COUNT(LOGDATE) >100



DECLARE @SEQ AS INT

SELECT @SEQ = SEQ FROM MASTER.DBO.splitWithSeq(@TEXT,' ')
WHERE items = '[CLIENT:'

SELECT @IP = items FROM MASTER.DBO.splitWithSeq(@TEXT,' ')
WHERE SEQ =@SEQ+1
SET @IP = REPLACE(@IP,']','')


SET @MSG = 'Your system is under attack! A machine with ip'
SET @MSG = @MSG + @IP
SET @MSG = @MSG + 'has tired' + CONVERT(VARCHAR,@COUNT) + 'wrong password between'
SET @MSG = @MSG + CONVERT(varchar,@BEGDATE,108) + ' and ' + CONVERT(varchar,@ENDDATE,108)
SELECT @MSG

IF @COUNT >100
BEGIN

INSERT INTO AUDIT.dbo.BRUTE_FORCE_ATTACK ([COMPUTERIP], [DATE_], [BEGDATE], [ENDDATE], [COUNT_])
VALUES(@IP,GETDATE(),@BEGDATE,@ENDDATE,@COUNT)

EXEC msdb.dbo.sp_send_dbmail
	@profile_name = 'SQLMAIL',
	@recipients = 'softwarehsp@gmail.com',
	@body = @MSG,
	@subject = 'Brute Force Attack Detected';
END



DROP TABLE #LOG


