---DATETIME---


--DATEADD
DECLARE @TARIH AS DATETIME
SET @TARIH ='2019-01-01 16:21:37'
--6 ay ekledik
DECLARE @TARIH2 AS DATETIME
SET @TARIH2 = DATEADD(MONTH,6,@TARIH)
SELECT @TARIH,@TARIH2

--DATEIF  2 TARIH ARASINDA FARK ALIR

DECLARE @TARIH AS DATETIME
SET @TARIH='2019-01-01 16:74:11'
DECLARE @TARIH2 AS DATETIME
SET @TARIH2 = '2020-01-01 14:14:21'

SELECT DATEIFF(MONTH,@TARIH,@TARIH2)

--DATEPART BIR TARIHIN İSTENİLDİĞİ KISMI GETİRİR

DECLARE @TARIH AS DATETIME
SET @TARIH = '2019-01-01 14:14:02'
SELECT DATEPART(DAY,@TARIH)


SELECT YEAR(@TARIH)


SELECT GETDATE() -- SİMDİKİ ZAMANI GETIRIR

--DOGUM TARIHI GIRILEN BIR KISININ YASINI HESAPLA

DECLARE @TARIH AS DATE
SET @TARIH ='2000-04-12'
SELECT DATEDIFF(YEAR,@TARIH,GETDATE())