SELECT * FROM CUSTOMERS WHERE NAMESURNAME = 'ADA SÖZÜER' AND BIRTHDATE = '1996-03-09'

SELECT COUNT(*) FROM CUSTOMERS WHERE BIRTHDATE = '1996-03-09'
SELECT COUNT(*) FROM CUSTOMERS WHERE NAMESURNAME = 'Ada Sözüer'

--BURADAN SONRASINI STORE PROCEDURE TOO