SELECT * FROM CUSTOMERS WHERE NAMESURNAME = 'ÖMER ÇOLAKOĞLU' AND  TCNO = '10019865823'

SET STATISTICS IO ON --Bu komud sistemde çalıştırdığımız sorgunun ne kadar yer kapladığını gösterir.


SELECT * FROM CUSTOMERS WHERE ID = 35578

UPDATE CUSTOMERS SET TCNO = '11111' WHERE ID = 35578   --VERİ GÜNCELLEME

--DUPLICATE TEKRAR EDEN VERİ OLARAK KARŞIMIZA GELİR.

