
CREATE TABLE PURT (ID INT IDENTITY(1,1),ISIM VARCHAR(20), TELEFON VARCHAR(12))

ALTER TABLE PURT ADD COMMUNATION VARCHAR(20) --Kayıt ekleme

ALTER TABLE PURT DROP COLUMN COMMUNATION --kolon silme

ALTER TABLE PURT ALTER COLUMN ISIM VARCHAR(50) --Kolon değiştirme

INSERT INTO PURT (ISIM) VALUES ('SEFA') --ekleme

SELECT * FROM PURT --getirme
 
DROP TABLE PURT --Tablo silme



