DECLARE @KELIME AS VARCHAR(100)
SET @KELIME = 'HELLO WORLD'    --SUBSTRING PARCALAMA İSLEMİ

SELECT SUBSTRING(@KELIME,1,7)

--LOWER, UPPER,

DECLARE @KELIME AS VARCHAR(20)  --kucuk harf
SET @KELIME = 'HI'
SELECT LOWER(@KELIME)



DECLARE @KELIME AS VARCHAR(20)  --Buyukharf harf
SET @KELIME = 'HI'
SELECT UPPER(@KELIME)



--STRING BİRSLETİRME

DECLARE @AD AS VARCHAR(100)='SEFA'
DECLARE @SOYAD AS VAHCHAR(100)='PINAR'

SELECT @AD+''+@SOYAD


--RIGHT,LEFT

DECLARE @KELIME AS VARCHAR(100)
SET @KELIME = 'Merhaba'
SELECT LEFT(@KELIME,1)

DECLARE @KELIME AS VARCHAR(100)
SET @KELIME = 'Merhaba'
SELECT RIGHT(@KELIME,1)


--LTRIM,RTRIM,TRIM BOŞLUK TEMİZLEYEN KOMUTLAR

DECLARE @KELIME AS VARCHAR(100)='  HELLO WORLD'
SELECT LTRIM(@KELIME)


DECLARE @KELIME AS VARCHAR(100)='  HELLO WORLD'
SELECT RTRIM(@KELIME)

DECLARE @KELIME AS VARCHAR(100)='  HELLO WORLD'
SELECT TRIM(@KELIME)


--REPLACE DEGISTIRME ISLEMI

DECLARE @KELIME AS VARCHAR (100)='MERHABA DÜNYA'
SELECT REPLACE(@KELIME,'MERHABA','HELLO')

--LEN STRING IFADENIN UZUNLUGUNU GETİRİR

DECLARE @KELIME AS VARCHAR(100)='Merhaba Dunya'
SELECT LEN (@KELIME)


--STRING SPLIT

DECLARE @KELIME AS VARCHAR(100)='HI WORLD' --TABLO OLARAK AYIRMA
SELECT * FROM string_split(@KELIME,' ')



