CREATE FUNCTION DBO.CALCULATE_AGE(@BIRTHDATE AS DATE)
RETURNS INT
AS
BEGIN
DECLARE @RESULT AS INT
SET @RESULT = DATEDIFF(YEAR,@BIRTHDATE,GETDATE())
RETURN @RESULT
END

SELECT DBO.CALCULATE_AGE('199000101')
