CREATE FUNCTION DBO.MONTHNAME_(@DATE AS DATETIME)
RETURNS VARCHAR(10)
AS
BEGIN
DECLARE @RESULT AS VARCHAR(10)

IF DATEPART(MONTH,@DATE) = 1 SET @RESULT = 'OCAK'
IF DATEPART(MONTH,@DATE) = 2 SET @RESULT = 'ARK'
IF DATEPART(MONTH,@DATE) = 3 SET @RESULT = 'SBK'
IF DATEPART(MONTH,@DATE) = 4 SET @RESULT = 'MRTK'
IF DATEPART(MONTH,@DATE) = 5 SET @RESULT = 'NSN'
IF DATEPART(MONTH,@DATE) = 6 SET @RESULT = 'MYSK'
IF DATEPART(MONTH,@DATE) = 7 SET @RESULT = 'HZRN'
IF DATEPART(MONTH,@DATE) = 8 SET @RESULT = 'TMMZ'
IF DATEPART(MONTH,@DATE) = 9 SET @RESULT = 'AGSK'
IF DATEPART(MONTH,@DATE) = 10SET @RESULT = 'EYLY'
IF DATEPART(MONTH,@DATE) = 11SET @RESULT = 'EKMK'
IF DATEPART(MONTH,@DATE) = 12SET @RESULT = 'KSM'




END