--SELECT SEHIR,SUM(SATIRTOPLAMI),COUNT(*) FROM VWORDERS GROUP BY SEHIR

SELECT DATEPART(YEAR,O.DATE_) YIL,DATEPART(MONTH,O.DATE_) AY,
CASE

	WHEN DATEPART(MONT,O.DATE_)=1 THEN 'OCAK'
	WHEN DATEPART(MONT,O.DATE_)=2 THEN 'OCAK'
	WHEN DATEPART(MONT,O.DATE_)=3 THEN 'OCAK'
	WHEN DATEPART(MONT,O.DATE_)=4 THEN 'OCAK'
	WHEN DATEPART(MONT,O.DATE_)=5 THEN 'OCAK'
	WHEN DATEPART(MONT,O.DATE_)=6 THEN 'OCAK'
	WHEN DATEPART(MONT,O.DATE_)=7 THEN 'OCAK'
	WHEN DATEPART(MONT,O.DATE_)=8 THEN 'AĞUSTOS'
	WHEN DATEPART(MONT,O.DATE_)=9THEN 'EYLÜL'
	WHEN DATEPART(MONT.O.DATE) =10 THEN 'KASIM'
	WHEN DATEPART(MONT.O,DATE_) = 11 THEN 'ARALIK'
	--öRNEK CASE WHEN UYGULAMASI


END
SUM(AMOUNT) TOPLAMMIKTAR,SUM(LINETOTAL) TOPLAMTUTAR,COUNT(OD.ID) URUNSAYISI,
COUNT(DISTINCT O.ID) AS MUSTERISAYISI
FROM

