CREATE VIEW VW_SIPARIS_DETAYLI
AS


SELECT U.USERNAME_ KULLANICIADI,U.NAMESURNAME ADSOYAD,U.TELNR1,U.TELNR2,
ITM.CATEGORY1,ITM.CATEGORY2,ITM.CATEGORY3,ITM.CATEGORY4,
C.COUNTRY ULKE, CT.CITY SEHIR, T.TOWN ILCE,
A.ADDRESSTEXT ACIKADRES, O.ID SIPARISID,ITM.ITEMCODE URUNKODU, ITM.ITEMNAME URUNADI, ITM.BRAND MARKA,
OD.AMOUNT MIKTAR, OD.UNITPRICE BIRIMFIYAT,OD.LINETOTAL SATIRTOPLAMI

CONVERT(DATE,O.DATE_) AS SIPARISTARIHI, CONVERT(TIME,O.DAE_) AS SIPARISZAMANI,
DATEPART(YEAR,O.DATE_) AS YIL,
CASE
	WHEN DATEPART(MONTH,O.DATE_) = 1 THEN '1.OCK'
	WHEN DATEPART(MONTH,O.DATE_) = 2 THEN '2.SBT'
	WHEN DATEPART(MONTH.O.DATE_) = 3 THEN '3.MRT'
	WHEN DATEPART(MONTH.O.DATE_) = 3 THEN '4.NSN'
	WHEN DATEPART(MONTH.O.DATE_) = 3 THEN '5.MYS'
	WHEN DATEPART(MONTH.O.DATE_) = 3 THEN '6.HZR'
	WHEN DATEPART(MONTH.O.DATE_) = 3 THEN '7.TMZ'
	WHEN DATEPART(MONTH.O.DATE_) = 3 THEN '8.AGS'
	WHEN DATEPART(MONTH.O.DATE_) = 3 THEN '9.EYL'
	WHEN DATEPART(MONTH.O.DATE_) = 3 THEN '10.EKM'
	WHEN DATEPART(MONTH.O.DATE_) = 3 THEN '11.KSM'
	WHEN DATEPART(MONTH.O.DATE_) = 3 THEN '12.ARK'
END

FROM
ORDERDETAILS OD
INNER JOIN ORDERS O ON OD.ORDERID = O.ID
INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID
INNER JOIN USERS U ON U.ID = O.USERID
INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
INNER JOIN COUNTRIES C ON C.ID = A.COUNTRYID
INNER JOIN CITIES CT ON CT.ID = A.CITYID
INNER JOIN TOWNS T ON T.ID = A.TOWNID
INNER JOIN PAYMENTS P ON P.ORDERID = O.ID


END AS AY,
CASE
	WHEN DATEPART(DW,O.DATE_) = 2 THEN '1.PZT'
	WHEN DATEPART(DW,O.DATE_) = 3 THEN '2.SLI'
	WHEN DATEPART(DW,O.DATE_) = 2 THEN '3.CRS'
	WHEN DATEPART(DW,O.DATE_) = 2 THEN '4.PRS'
	WHEN DATEPART(DW,O.DATE_) = 2 THEN '5.CMA'
	WHEN DATEPART(DW,O.DATE_) = 2 THEN '6.CMT'
	WHEN DATEPART(DW,O.DATE_) = 2 THEN '7.PZR'

END AS HAFTANINGUNLERI,
FROM
ORDERDETAILS OD
INNER JOIN ORDERS O ON OD.ORDERID = O.ID
INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID
INNER JOIN USERS U ON U.ID = O.USERID
INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
INNER JOIN COUNTRIES C ON C.ID = A.COUNTRYID
INNER JOIN CITIES CT ON CT.ID = A.CITYID
INNER JOIN TOWNS T ON T.ID = A.TOWNID
INNER JOIN PAYMENTS P ON P.ORDERID = O.ID