SELECT * INTO --HER HANGI BIR TABLODAN DONEN SONUCU BİZİM İSTEDİĞİMİZ TABLOYA OLUSTURUR.

SELECT * INTO DATES3 FROM DATES


SELECT * INTO DATES4 FROM DATES
SELECT * INTO DATES5 FROM DATES
SELECT * INTO DATES6 FROM DATES
SELECT * INTO DATES7 FROM DATES
SELECT * INTO DATES8 FROM DATES
SELECT * INTO DATES9 FROM DATES
SELECT * INTO DATES10 FROM DATES

SP_SPACEUSED 'DATES'
SELECT * INTO DATES11 FROM DATES

