--DECLARE @ITEMID AS INT
--DECLARE @AMOUNT AS INT
--DECLARE @IOTYPE AS SMALLINT
--DECLARE @DATE AS DATETIME
--SET @ITEMID = ROUND(RAND()*4,0)
--IF @ITEMID = 0
--	SET @ITEMID = 1

--SET @DATE = DATEADD(DAY,-ROUND(RAND()*356,0), GETDATE())

--SET @AMOUNT = ROUND(RAND()*10,0)+1

--SET @IOTYPE = ROUND(RAND()*1,0)+1 --BİR LE İKİ ARASINDA DEĞER ALIR

--SELECT @ITEMID AS ITEMID, @DATE AS DATE_, @AMOUNT AS AMOUNT, @IOTYPE AS IOTYPE
----SELECT GETDATE() -- Simdiki zamanı getirir.


--SELECT * FROM ITEMS

--INSERT INTO ITEMTRANSACTIONS
--(ITEMID,DATE_,AMOUNT,IOTYPE)

--VALUES(@ITEMID,@DATE,@AMOUNT,@IOTYPE)

--SELECT * FROM ITEMTRANSACTIONS

DECLARE @I AS INT=0

WHILE @I<100   --RASTGELE DEĞER ÜRETEN UYGULAMA
BEGIN
	DECLARE @ITEMID AS INT
	DECLARE @DATE AS DATETIME
	DECLARE @AMOUNT AS INT
	DECLARE @IOTYPE AS SMALLINT

	SET @ITEMID=ROUND(RAND()*500,0)
	IF @ITEMID=0
		SET @ITEMID=1
	SET @DATE=DATEADD(DAY,-ROUND(RAND()*365,0), GETDATE())
	SET @AMOUNT=ROUND(RAND()*9,0)+1
	SET @IOTYPE=ROUND(RAND()*1,0)+1
	INSERT INTO ITEMTRANSACTIONS
	(ITEMID,DATE_,AMOUNT,IOTYPE)
	VALUES (@ITEMID,@DATE,@AMOUNT,@IOTYPE)
 SET @I=@I+1
END

SELECT * FROM ITEMTRANSACTIONS 