CREATE TRIGGER TRG_TRANSACTION_DELETE
ON ITEMTRANSACTIONS
AFTER DELETE
AS
BEGIN
	DECLARE @ITEMID AS INT
	DECLARE @DATE AS DATETIME
	DECLARE @AMOUNT AS INT
	DECLARE @IOTYPE AS SMALLINT

	SELECT @ITEMID=ITEMID,@AMOUNT=AMOUNT,@IOTYPE = IOTYPE FROM DELETED

	IF @IOTYPE = 1
		UPDATE STOCK SET STOCK = STOCK - @AMOUNT WHERE ITEMID = @ITEMID
	IF @IOTYPE =2
		UPDATE STOCK SET STOCK = STOCK + @AMOUNT WHERE ITEMID = @ITEMID
		


END --TOPLAMA