DECLARE @I AS INT =1

WHILE @I<=1000
BEGIN
	EXEC GENERATE_WORKER_TRANSACTION @I
SET @I = @I +1
END


SELECT MAX(WORKERID),COUNT(*) FROM WORKERTRANSACTIONS

SELECT * FROM WORKERS WHERE ID = 1

SELECT *, (SELECT TOP 1 IOTYPE FROM WORKERTRANSACTIONS WHERE WORKERID = W.ID ORDER BY DATE_ DESC) SONHAREKETTURU,
(SELECT MAX(DATE_) FROM WORKERTRANSACTIONS WHERE WORKERID = W.ID) SONHAREKETZAMANI
FROM WORKERS W
WHERE ID = 1
