
TRUNCATE TABLE ITEMTRANSACTIONS --TABLO SIFIRLAMA

SELECT * FROM ITEMTRANSACTIONS


INSERT INTO ITEMTRANSACTIONS(ITEMID,AMOUNT,IOTYPE,DATE_)
VALUES(1,5,1,GETDATE())


UPDATE STOCK SET STOCK = STOCK + 5 WHERE ITEMID = 1

SELECT * FROM STOCK