SET STATISTICS IO ON
SELECT ID,(SELECT SUM(AMOUNT) FROM ITEMTRANSACTIONS WHERE ITEMID = ITM.ID AND IOTYPE =1)
-
(SELECT SUM(AMOUNT) FROM ITEMTRANSACTIONS WHERE ITEMID = ITM.ID AND IOTYPE =2 ) AS STOK
FROM ITEMS ITM
ORDER BY ID

SELECT * FROM STOCK

TRUNCATE TABLE ITEMTRANSACTIONS

SELECT * FROM STOCK WHERE STOCK <>0