--TRIGGER İLE SON KAYDI ALMAK VE PERFORMANS IYILESTIRMEK

INSERT INTO WORKERS
(WORKERCODE,WORKERNAME,GENDER,BIRTHDATE,TCNO,WORKERBARCODE)





SELECT WORKERCODE,WORKERNAME,GENDER,BIRTHDATE,TCNO,WORKERBARCODE FROM WORKERS

SELECT TOP 1000
TCNO AS WORKERCODE, NAMESURNAME AS WORKERNAME, GENDER, BIRTHDATE, TCNO,NEWID() AS WORKERBARCODE

FROM CRM2.DBO.CUSTOMERS

SELECT * FROM WORKERS

