CREATE TRIGGER TRG_TRANSACTION_UPDATE
ON ITEMTRANSACTIONS
AFTER UPDATE
AS
BEGIN

DECLARE @ITEMID AS INT
DECLARE @IOTYPE AS INT
DECLARE @OLDAMOUNT AS INT
DECLARE @NEWAMOUNT AS INT
DECLARE @AMOUNT AS INT

SELECT @ITEMID = ITEMID, @IOTYPE = IOTYPE, @OLDAMOUNT = AMOUNT FROM DELETED

SELECT @NEWAMOUNT = AMOUNT FROM INSERTED


SELECT  @AMOUNT = @OLDAMOUNT - @NEWAMOUNT

IF @IOTYPE =1
	UPDATE STOCK SET STOCK = STOCK  - @AMOUNT WHERE ITEMID = @ITEMID 

IF @IOTYPE = 2
	UPDATE STOCK SET STOCK = STOCK + @AMOUNT WHERE ITEMID = @ITEMID 

END  --UPDATED