
SELECT * FROM MONEYTRANSACTIONS
SELECT C.CUSTOMERNAME, A.ACCOUNTNO,A.ACCOUNTNAME,A.CURRENCY,B.BALANCE FROM ACCOUNTBALANCE B
INNER JOIN ACCOUNTS A ON A.ID = B.ACCOUNTID
INNER JOIN CUSTOMERS C ON C.ID = A.CUSTOMERID

BEGIN TRAN
INSERT INTO MONEYTRANSACTIONS
(ACCOUNTID,TRANTYPE,AMOUNT,DATE_,EFTCODE,EFTCODE2)
VALUES
(1,2,1000,'20200414 14:20:11','12321','')
IF @@ERROR >0
BEGIN
	ROLLBACK TRAN
	RETURN
END

UPDATE ACCOUNTBALANCE SET BALANCE = BALANCE -1000 WHERE ACCOUNTID=1
IF @@ERROR >0
BEGIN	
	ROLLBACK TRAN
	RETURN
END

INSERT INTO MONEYTRANSACTIONS
(ACCOUNTID,TRANTYPE,AMOUNT,DATE_,EFTCODE,EFTCODE2)
VALUES
(2,1,1000,'20211010 15:21:30','12323','2323')
IF @@ERROR >0
BEGIN
	ROLLBACK TRAN
	RETURN

END
	


