SELECT * FROM WORKERS WHERE WORKERBARCODE = '29A18D9B-1F57-435E-91AA-EFCAA9B893ED'



ALTER PROCEDURE SP_CARD_CONTROL
@WORKERBARCODE AS VARCHAR(50)
AS
BEGIN
	DECLARE @WORKERNAME AS VARCHAR(100)
	SELECT @WORKERNAME = WORKERNAME WHERE WORKERBARCODE = @WORKERBARCODE
	IF @WORKERNAME IS NULL
	BEGIN
	SELECT 'KART BULUNAMADI'
	END
	ELSE
	BEGIN
	SELECT @WORKERNAME
	END


	SELECT @WORKERNAME

	IF EXISTS(SELECT * FROM WORKERS WHERE WORKERBARCODE = @WORKERBARCODE)
	BEGIN
	SELECT 'KART DOĞRU'
	END
	ELSE
	BEGIN
	SELECT 'KART GEÇERSİZ'
	END

	




END