CREATE PROC SP_WORKER_INOUT

@WORKBARCODE AS VARCHAR(59),
@DATE AS DATETIME,
@IOTYPE AS VARCHAR(1),
@GATEID AS INT 
AS
BEGIN
DECLARE @WORKERNAME AS VARCHAR(100)
DECLARE @WORKERID AS INT

SELECT @WORKERNAME = WORKERNAME, @WORKERID =ID FROM WORKERS WHERE WORKERBARCODE = @WORKBARCODE

	IF @WORKERID IS NULL
		BEGIN
		RAISERROR ('OKUTULAN KART GEÇERSİZ',16,1)
		RETURN
	END

DECLARE @LASTIO AS VARCHAR(1)

SELECT TOP 1 @LASTIO=IOTYPE FROM WORKERTRANSACTIONS WHERE WORKERID = 1 AND DATE_>=CONVERT(DATE,GETDATE())
ORDER BY DATE_ DESC --SONDAN AŞAĞIYA DOĞRU YAKALADI


	IF @LASTIO = @IOTYPE
	BEGIN
		IF @IOTYPE = 'G'
		BEGIN
			RAISERROR('ZATEN İÇERİDE GÖRÜYORSUNUZ',16,1)
			RETURN
		END
			IF @IOTYPE='C'
		BEGIN
			RAISERROR('ZATEN DIŞARIDA GÖRÜNÜYORSUNUZ, ÇIKIŞ YAPAMAZSINIZ',16,1)
			RETURN
		END
	END

	INSERT INTO WORKERTRANSACTIONS (WORKERID,DATE_,IOTYPE,GATEID)
	VALUES(@WORKERID,@DATE,@GATEID,@IOTYPE)

	SELECT @WORKERNAME AS WORKERNAME, @DATE AS DATE_, @IOTYPE AS IOTYPE





END