SELECT ITM.ITEMCODE MALZEMEKODU, ITM.ITEMNAME MALZEMEADI

(SELECT MIN(UNITPRICE) FROM ORDERDETAILS OD WHERE OD.ITEMID = ITM.ID) AS ENDUSUKFIYAT
(SELECT MAX(UNITPRICE) FROM ORDERDETAILS OD WHERE OD.ITEMID = ITM.ID) AS ENYUKSEKFIYAT

FROM ITEMS ITM