CREATE FUNCTION DBO.GET_ITEM_MIN_PRICE(@ITEMID AS INT)
RETURNS FLOAT
AS
BEGIN
DECLARE @RESULT AS FLOAT
SELECT @RESULT

	SELECT @RESULT = MIN(UNITPRICE) FROM ORDERDETAILS OD WHERE OD.ITEMID = @ITEMID
	RETURN @RESULT 


END